# 프로젝트 기본 인코딩 x-windows-949  
# 설정파일만 UTF-8 로 지정

server:
  port: 7777 # 스프링 부트 내장 서버 포트

logging:
  level:
#    org.hibernate.SQL: debug // 쿼리 확인가능
#    org.hibernate.type.descriptor.sql: trace // 쿼리 확인가능
    root: INFO
    org.springframework: DEBUG
    com.example: TRACE
    com.zaxxer.hikari: DEBUG

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: SQLP
    password: SQLP2

    # 기본 커넥션풀 설정
    hikari:
      maximum-pool-size: 10        # 동시에 연결 유지할 커넥션 수
      minimum-idle: 5              # 유휴 커넥션 최소 유지 수
      connection-timeout: 30000    # 커넥션 대기 최대 시간 (ms)
      idle-timeout: 600000         # 유휴 상태 유지 시간 (ms)
      max-lifetime: 1800000        # 커넥션 최대 수명 (ms)

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true